name = "JCGECalibrate"
uuid = "52bcf1bb-5715-4bdb-b809-8ade53bb6205"
authors = ["Riccardo Boero <ribo@nilu.no>"]
version = "0.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
